// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmd7DiavOwGBmtN687sn_gHwGt3jgLdKA',
    appId: '1:848207481227:web:579590c650cece08ab078e',
    messagingSenderId: '848207481227',
    projectId: 'dispatchmanagement-3f886',
    authDomain: 'dispatchmanagement-3f886.firebaseapp.com',
    databaseURL: 'https://dispatchmanagement-3f886-default-rtdb.firebaseio.com',
    storageBucket: 'dispatchmanagement-3f886.firebasestorage.app',
    measurementId: 'G-JFDY0QD9CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChyUJowRmc0WqVQuXym-cLl2AwSZ-piPE',
    appId: '1:848207481227:android:a6510ca0934e1a9cab078e',
    messagingSenderId: '848207481227',
    projectId: 'dispatchmanagement-3f886',
    databaseURL: 'https://dispatchmanagement-3f886-default-rtdb.firebaseio.com',
    storageBucket: 'dispatchmanagement-3f886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKic4cyiQecFW8JPcQds0GbUVrzmEXeog',
    appId: '1:848207481227:ios:d664020316a0c102ab078e',
    messagingSenderId: '848207481227',
    projectId: 'dispatchmanagement-3f886',
    databaseURL: 'https://dispatchmanagement-3f886-default-rtdb.firebaseio.com',
    storageBucket: 'dispatchmanagement-3f886.firebasestorage.app',
    iosBundleId: 'com.example.dispatchManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmd7DiavOwGBmtN687sn_gHwGt3jgLdKA',
    appId: '1:848207481227:web:e49d11bc42838489ab078e',
    messagingSenderId: '848207481227',
    projectId: 'dispatchmanagement-3f886',
    authDomain: 'dispatchmanagement-3f886.firebaseapp.com',
    databaseURL: 'https://dispatchmanagement-3f886-default-rtdb.firebaseio.com',
    storageBucket: 'dispatchmanagement-3f886.firebasestorage.app',
    measurementId: 'G-H6E9TCWM72',
  );
}
